In [23]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import FastICA
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
data=load_iris()
x=data.data
y=data.target
p=pd.DataFrame(x,columns=data.feature_names)
g=pd.DataFrame(y,columns=['target'])
print(p.shape)
p.head()

(150, 4)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
g.head()

   target
0       0
1       0
2       0
3       0
4       0

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_train)
fa=FastICA(n_components=3, max_iter=1000, tol=1e-3, random_state=42)
x_fa=fa.fit_transform(x_scaled)
x_fas=pd.DataFrame(x_fa,columns=['IC1','IC2','IC3'])
print(x_fas.shape)
x_fas

(120, 3)

          IC1       IC2       IC3
0    1.318311 -1.286143 -0.092595
1    1.847300 -0.854241  2.219879
2   -0.909869  0.274139  1.174870
3    0.587224 -1.229831 -0.029521
4    0.717145 -1.316253 -0.845296
..        ...       ...       ...
115 -0.871999  0.059933  0.053237
116  1.046252  0.618052 -2.651340
117  0.370162 -1.258239  2.219462
118 -1.031159 -0.063262 -0.523494
119 -0.481110  1.229774  0.827554

[120 rows x 3 columns]

In [38]:
model=LogisticRegression()
model.fit(x_fas,y_train)
x_test_scaled=scaler.transform(x_test)
x_test_fa=fa.transform(x_test_scaled)
x_test_fas=pd.DataFrame(x_test_fa,columns=['IC1','IC2','IC3'])
y_pred=model.predict(x_test_fas)
y_pred
print(y_preds)
print(y_preds.shape)
print("accuracy_score:",accuracy_score(y_test,y_pred))

    output
0        1
1        0
2        2
3        1
4        1
5        0
6        1
7        2
8        1
9        1
10       2
11       0
12       0
13       0
14       0
15       1
16       2
17       1
18       1
19       2
20       0
21       2
22       0
23       2
24       2
25       2
26       2
27       2
28       0
29       0
(30, 1)
accuracy_score: 1.0

In [36]:
print("Train score:",model.score(x_fas,y_train))
print("Test score:",model.score(x_test_fas,y_test))
print("accuracy_score:",accuracy_score(y_test,y_pred))
print(p.shape)
print(x_fas.shape)
print(p.head())
print(x_fas.head())

Train score: 0.9166666666666666
Test score: 0.9
accuracy_score: 0.9
(150, 4)
(120, 2)
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
        IC1       IC2
0 -0.485130 -1.594225
1 -2.756090 -1.211774
2 -0.533860  0.561559
3 -0.156014 -1.341939
4  0.470046 -1.497870

In [22]:
fa.components_

array([[ 0.8773762 , -0.41390433,  0.99878951,  0.96085711],
       [-0.46077849, -0.55140777,  0.03084212,  0.08403235]])